SkycoinProject/skycoin

CHANGELOG.md, src/visor/db.go
Fixes #26
Changes:
- Add additional database corruption checks in ResetCorruptDB to detect encoder ErrBufferUnderflow and ErrMaxLenExceeded
This may need more detailed review from the team. Refer to Issue #26 for my analysis of the issues.
Yes. Included in PR
=> Add new database corruption checks in ResetCorruptDB 

.travis.yml, CHANGELOG.md, src/kvstorage/kvstorage.go, src/kvstorage/kvstorage_test.go
Fixes #7 #162
Changes:
- When loading kvstorage file failed due to the corrupted file, then backup it and create a new empty file. 
- Add unit tests
Yes.
=> Fix corrupted kvstorage file

src/api/integration/wallet_test.go, src/api/wallet_test.go, src/util/file/file.go, src/util/file/file_test.go, src/wallet/service.go, src/wallet/service_test.go, src/wallet/wallet.go
Fixes #104
Changes:
- ~~Check if the wallet exists before saving~~
- Removing tmp file in `defer` so that the tmp file would be removed after leaving `func SaveBinary()`. We write data to tmp file cause we don't want users to lose their coins if there's power down when saving their wallet files. 
Todo:
Yes
=> Fix inconsistent wallet state after saving failed

CHANGELOG.md, README.md, cmd/skycoin-cli/README.md, src/cli/cli.go, src/cli/create_rawtx.go, src/cli/integration/integration_test.go, src/cli/transaction.go
Fixes #165, #135 
Changes:
- Add `signTransaction` cli command to sign transaction
- Add `createRawTransactionV2` cli command, which provides the `--unsign` option to create a transaction without signing.
Before adding the `createRawTransactionV2` command, it is difficult to create an unsigned transaction. The only way to do this is calling the api of `/wallet/transaction`. 
TODO:
Yes
=> Add cli command to create/sign a transaction

ci-scripts/lint-and-test.sh
Changes:
- Add `set -e -o pipefail` to the `ci-scripts/lint-and-test.sh` so that the travis build won't ignore the errors the script returns.
No
=> Break the travis build if has lint error

docker/images/mainnet/hooks/build
Changes:
- Update the docker build cache tag name, as we're now using the tag name directly without the prefix of `release-`. 
- Fix incorrect docker hub organization name.
No
=> Update the docker build cached tag name

CHANGELOG.md, ci-scripts/integration-test-stable.sh, src/api/integration/testdata/address-transactions-2jBbGxZRGoQG1mqhPBnXnLTxK6oxsTf8os6.golden, src/api/integration/testdata/address-transactions-ALJVNKYL7WGxFBSriiZuwZKWD4b7fbV1od.golden, src/api/integration/testdata/address-transactions-R6aHqKWSQfvpdo2fGSrq4F1RYXkBWR9HHJ.golden, src/api/integration/testdata/address-transactions-incoming-212mwY3Dmey6vwnWpiph99zzCmopXTqeVEN.golden, src/api/integration/testdata/address-transactions-outgoing-R6aHqKWSQfvpdo2fGSrq4F1RYXkBWR9HHJ.golden, src/api/integration/testdata/all-unconfirmed-txns-verbose.golden, src/api/integration/testdata/block-hash-verbose.golden, src/api/integration/testdata/block-last-verbose.golden, src/api/integration/testdata/block-seq-verbose-1.golden, src/api/integration/testdata/block-seq-verbose-100.golden, src/api/integration/testdata/blocks-3-5-7-verbose.golden, src/api/integration/testdata/blocks-verbose-all.golden, src/api/integration/testdata/blocks-verbose-first-1.golden, src/api/integration/testdata/blocks-verbose-first-10.golden, src/api/integration/testdata/blocks-verbose-last-10.golden, src/api/integration/testdata/confirmed-and-unconfirmed-transactions-verbose.golden, src/api/integration/testdata/empty-addrs-transactions-verbose.golden, src/api/integration/testdata/genesis-addr-transactions-verbose.golden, src/api/integration/testdata/multiple-addr-transactions-verbose.golden, src/api/integration/testdata/single-addr-transactions-verbose.golden, src/api/integration/testdata/transaction-unconfirmed-verbose.golden, src/api/integration/testdata/transaction-verbose-block-101.golden, src/api/integration/testdata/transaction-verbose-block-517.golden, src/api/integration/testdata/unconfirmed-excluded-from-transactions-verbose.golden, src/api/integration/testdata/verbose-pending-transactions.golden, src/api/transaction_test.go, src/readable/transaction.go
Fixes #59 
Changes:
-  Add `src_txid` to verbose transaction inputs, the following APIs will be affected:
```
/api/v1/transaction
/api/v1/transactions
/api/v1/block
/api/v1/blocks
/api/v1/pendingTxs
```
- Update unit tests and integration tests
Yes.
=> Add src_txid to verbose transaction inputs

electron/build-electron-release.sh
Fixes #120
Changes:
- Zip linux AppImage file so that the executable attribute could be retained after uploading to aws s3 bucket.
No.
=> Zip linux AppImage file

CHANGELOG.md, run-client.sh, run-daemon.sh, src/api/gateway.go, src/api/http.go, src/api/http_test.go, src/api/mock_gatewayer_test.go, src/api/wallet.go, src/api/wallet_test.go, src/wallet/bip44_wallet.go, src/wallet/deterministic_wallet.go, src/wallet/service.go, src/wallet/service_test.go
Fixes #200 
Changes:
- Add API endpoint `/api/v1/wallet/scan`, which will scan ahead addresses as required
- Add unit tests  for `service.ScanAddresses` function
Todo:
Yes,
=> Add  wallet address scanning API

src/api/README.md
Changes:
- A link to the `Get transactions with pagination` section was added to the API documentation.
No
=> Add a missing link to the API documentation

.travis.yml, ci-scripts/add-key.sh
Fixes #231 
Changes:
- Update `osx_image` from `xcode8` to `xcode11`
- Fix osx code signing issue that caused by the updating of osx image
No
=> Update osx_image to adapt the updating of electron

CHANGELOG.md, src/api/http.go, src/skycoin/db_check.go, src/skycoin/db_check_test.go, src/skycoin/skycoin.go, src/visor/transaction_model.go
Fixes #229 
Changes:
- Update check point to v0.27.0
- Do not update DB version unless the DB structure is changed. 
- Remove the App version from the DB version verify logic. We only need to check if the DB version is equal to the check point. If the DB version is less than the check point, check the DB reset if needed. If the DB version is equal to the check point, then we don't need to check the DB. If the DB version is greater than the  check point, return error.
- Update changelog.
Yes, Updated.
=> Update db version when needed

src/visor/dbutil/dbutil.go
Fixes #54 
Changes:
- Use `bucket.Cursor().First()` to check if the bucket is empty. 
No.
=> Use bucket.Cursor().First() to check if bucket is empty

src/cli/address_gen.go, src/util/file/file.go
Fixes #88 
Changes:
- Call `file.Sync()` to flush the data on buffer if any before closing file. 
No.
=> Check defer file.Close() error on writeable file

src/gui/static/src/app/components/pages/settings/backup/backup.component.html, src/gui/static/src/app/components/pages/settings/backup/backup.component.scss, src/gui/static/src/app/components/pages/settings/backup/backup.component.ts, src/gui/static/src/assets/i18n/en.json, src/gui/static/src/assets/i18n/es.json, src/gui/static/src/assets/i18n/es_base.json
Fixes #269
Changes:
- The page for creating wallet backups now has a link for making the browser download a csv file with all the addresses of the wallets.
- Now the page for creating wallet backups shows all the wallets and not just the encrypted ones, as it is possible to create csv files for all wallets. If a wallet is not encrypted, the option for checking the seed is not active and the user can see a help msg.
No
=> Allow to save the addresses of a wallet as a CSV file

src/gui/static/src/app/utils/errors.ts, src/gui/static/src/assets/i18n/en.json, src/gui/static/src/assets/i18n/es.json, src/gui/static/src/assets/i18n/es_base.json
Fixes #281 
Changes:
- The errors from https://github.com/SkycoinProject/skycoin/blob/develop/src/transaction/params.go#L37-L62 are now caught in the front end and are replaced with different translatable error messages. Also, the error message returned when the change output is repeated is caught.
No
=> Improved error messages in the UI

src/gui/static/src/app/app.component.html, src/gui/static/src/styles.scss
Changes:
- Using Electron, if a modal window is opened while the content has been scrolled, the background color is not shown as it should:
This PR solves that problem.
No
=> Fix a problem with the background color

src/wallet/bip44wallet/account.go, src/wallet/bip44wallet/account_test.go
Fixes:
The node reported a panic error when handling the newAddress API request for an existing bip44 wallet. It panics because the bip44 chains do not have the address decoder recovered when recovering from a readable wallet. We can fix it by init the address decoder, however that may not be a good practice for the wallet API, as users can easily forget the init of chain decoder. Instead we should force user to pass the decoder as a param when call the `newAddresses` method.
No
=> Fix bip44 wallet newAddress error for existing wallet

README.md, ci-scripts/lint-and-test.sh
Changes:
- The procedure for checking the translation files was removed from the Travis tests. This is because the current setup requires all the translation files to be updated in order to pass the Travis test, which is inconvenient, as some PRs will include changes for the UI texts but it will not be possible to make all the translations before creating the PR. An example of this is https://github.com/SkycoinProject/skycoin/pull/303 , which includes a new string for the UI but lacks the Chinese translation.
- A section with info about checking the translation files was added to the main readme file.
No
=> Remove the translation check from Travis

src/gui/static/src/app/utils/errors.ts, src/gui/static/src/assets/i18n/en.json, src/gui/static/src/assets/i18n/es.json, src/gui/static/src/assets/i18n/es_base.json
Changes:
- Currently, when trying to load a wallet that is already on the wallet list, the error message shown is `500 Internal Server Error - fingerprint conflict for "deterministic" wallet.`. This PR changes it to `A wallet for the specified seed already exists.`.
No
=> Better error msg for repeated wallets
